env: "prod" # local, dev, prod 

rabbitmq:
  url: "amqp://user:password@rabbitmq:5672/"
  queue_name: "msgQueue"

email:
  host: "smtp.gmail.com"
  port: 587
  username: "" # email отправителя
  password: "" # пароль от email