env: "prod" # local, dev, prod 

tokens:
  access_token_ttl: 1h
  refresh_token_ttl: 168h
  verification_token_ttl: 15m
  verification_token_secret: "123o;rnfdjh1^%I@!$N&RJHDF*&T!#@$HADF&T"

http_server:
  address: ":8082"
  timeout: 4s
  idle_timeout: 30s

postgres:
  host: "postgres"
  port: 5432
  user: "user"
  password: "password"
  dbname: "auth_service"
  sslmode: "disable"

rabbitmq:
  url: "amqp://user:password@rabbitmq:5672/"
  queue_name: "msgQueue"
